-- Seed a tiny US core pack into food_items so backend indexed search
-- has immediate supermarket-brand coverage before larger pack ingests.

insert into public.food_items (
  id,
  region,
  language,
  source,
  name,
  brand,
  barcode,
  kcal_100g,
  protein_g_100g,
  carbs_g_100g,
  fat_g_100g,
  serving_summary,
  name_normalized,
  popularity_region_score,
  updated_at
)
values
  (
    'seed-us-kirkland-protein-bar',
    'US',
    'en',
    'INTERNAL',
    'Protein Bar, Chocolate Chip Cookie Dough',
    'Kirkland Signature',
    null,
    401,
    31,
    40,
    14,
    '{"label":"1 bar","grams":60}'::jsonb,
    'protein bar chocolate chip cookie dough',
    0.71,
    now()
  ),
  (
    'seed-us-great-value-greek-yogurt',
    'US',
    'en',
    'INTERNAL',
    'Greek Nonfat Yogurt, Plain',
    'Great Value',
    null,
    59,
    10,
    3.8,
    0.2,
    '{"label":"170 g cup","grams":170}'::jsonb,
    'greek nonfat yogurt plain',
    0.79,
    now()
  ),
  (
    'seed-us-equate-electrolyte',
    'US',
    'en',
    'INTERNAL',
    'Electrolyte Drink, Lemon Lime',
    'Equate',
    null,
    24,
    0,
    6,
    0,
    '{"label":"12 fl oz","ml":355}'::jsonb,
    'electrolyte drink lemon lime',
    0.62,
    now()
  ),
  (
    'seed-us-simple-truth-granola',
    'US',
    'en',
    'INTERNAL',
    'Granola, Oats & Honey',
    'Simple Truth',
    null,
    451,
    10,
    67,
    16,
    '{"label":"2/3 cup","grams":64}'::jsonb,
    'granola oats honey',
    0.58,
    now()
  ),
  (
    'seed-us-private-selection-bread',
    'US',
    'en',
    'INTERNAL',
    'Multigrain Bread',
    'Private Selection',
    null,
    265,
    10,
    43,
    6,
    '{"label":"1 slice","grams":34}'::jsonb,
    'multigrain bread',
    0.55,
    now()
  ),
  (
    'seed-us-good-gather-ketchup',
    'US',
    'en',
    'INTERNAL',
    'Tomato Ketchup',
    'Good & Gather',
    null,
    112,
    1.3,
    26,
    0.1,
    '{"label":"1 tbsp","grams":17}'::jsonb,
    'tomato ketchup',
    0.49,
    now()
  ),
  (
    'seed-us-market-pantry-peanut-butter',
    'US',
    'en',
    'INTERNAL',
    'Creamy Peanut Butter',
    'Market Pantry',
    null,
    588,
    25,
    20,
    50,
    '{"label":"2 tbsp","grams":32}'::jsonb,
    'creamy peanut butter',
    0.60,
    now()
  ),
  (
    'seed-us-members-mark-protein-shake',
    'US',
    'en',
    'INTERNAL',
    'Protein Shake, Chocolate',
    'Member''s Mark',
    null,
    67,
    10,
    4.7,
    1.1,
    '{"label":"11 fl oz","ml":325}'::jsonb,
    'protein shake chocolate',
    0.57,
    now()
  ),
  (
    'seed-us-trader-joes-greek-yogurt',
    'US',
    'en',
    'INTERNAL',
    'Greek Yogurt, Plain',
    'Trader Joe''s',
    null,
    59,
    10,
    3.6,
    0.4,
    '{"label":"170 g cup","grams":170}'::jsonb,
    'greek yogurt plain',
    0.53,
    now()
  ),
  (
    'seed-us-simply-nature-oats',
    'US',
    'en',
    'INTERNAL',
    'Old Fashioned Oats',
    'Simply Nature',
    null,
    389,
    16.9,
    66.3,
    6.9,
    '{"label":"1/2 cup dry","grams":40}'::jsonb,
    'old fashioned oats',
    0.46,
    now()
  )
on conflict (id) do update set
  region = excluded.region,
  language = excluded.language,
  source = excluded.source,
  name = excluded.name,
  brand = excluded.brand,
  barcode = excluded.barcode,
  kcal_100g = excluded.kcal_100g,
  protein_g_100g = excluded.protein_g_100g,
  carbs_g_100g = excluded.carbs_g_100g,
  fat_g_100g = excluded.fat_g_100g,
  serving_summary = excluded.serving_summary,
  name_normalized = excluded.name_normalized,
  popularity_region_score = excluded.popularity_region_score,
  updated_at = now();
